apiVersion: v1
kind: Service
metadata:
  name: deno-health
  labels:
    app.kubernetes.io/name: deno-health
spec:
  selector:
    app.kubernetes.io/name: deno-health
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-health
  labels:
    app.kubernetes.io/name: deno-health
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deno-health
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deno-health
    spec:
      containers:
      - name: deno-health
        image: deno-health:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deno-health
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deno-health
  endpoints:
  - port: web

